### ISSUE TITLE
Adding class in the div for images 

### ISSUE THREAD

**Issue by Mannaio** [pioul/jQuery.SimpleSelect#1]
This plugin seems really nice and straightforward, but i would need the possibility also to add images in any div list element, like for example adding a class. There is any demo or recommendation to achieve that?

Thanks

**Comment by pioul** [comment]
I'm adding this to my todo list, and closing this issue. I probably won't have time to work on it in the near future, so feel free to fork the plugin and send a PR, I'll review it in no time. Otherwise I'll comment here when that feature lands in SimpleSelect.

Cheers!
